### ISSUE TITLE
OUT přepisování

### ISSUE THREAD

**Issue by Jenyk** [moravianlibrary/AbbyyRest#1]
Dá se nastavit, aby se případné existující (z nějakého důvodu nesmazané) soubory v OUT přepisovaly?
Teď se tam vytvoří soubory se suffixem .001.xml atd.

**Comment by popelkatomas** [comment]
Ověřím dnes, nebude-li možné ošetřit systémově, vyřeším v kódu

**Comment by popelkatomas** [comment]
Na latinkovém recognition serveru vyřešeno nastavením workflow, na frakturovém nelze, v případě potřeby issue znovu otevřít, bude ošetřeno na úrovni kódu.
